### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by DanielGurianov** [Revadike/SteamKey.Trade#5] opened 2024-12-15 18:43 UTC
Make Sync work-
Syncing owned apps/packages,
Preferably much better than barters, with demo syncing and correct package syncing.

If possible make an even better sync- 
Packages that are not owned directly but have all the contents inside them already owned from other packages also show as owned.

Ofc, also syncing wishlist

**Comment by Revadike** [comment] 2024-12-16 14:05
Duplicate of #68 
Duplicate of #57

**Comment by Revadike** [comment] 2024-12-16 14:05
Duplicate of #68 #57

**Comment by Revadike** [comment] 2024-12-16 14:06
Duplicate of #57

**Closed** 2024-12-16 14:06 UTC
Labels: duplicate, feature
