### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by DanielGurianov** [Revadike/SteamKey.Trade#4] opened 2024-12-15 18:39 UTC
Pretty self explanatory, let users get notified when X happens.
X:
New incoming trades,
New Accepted offers,
New Bundle (Are we doing bundles like barter or naw?),
New comment –
From user trading with
From another community member
---all with options to enable / disable.

**Comment by Revadike** [comment] 2024-12-15 21:35
Dupe of https://github.com/Revadike/SteamKey.Trade/issues/51

**Comment by Revadike** [comment] 2024-12-16 13:58
Duplicate of #51

**Closed** 2024-12-16 13:58 UTC
Labels: duplicate
